name: Auto-assign PR to author

on:
  # Use pull_request_target so it works for PRs from forks, too
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const author = pr.user.login;

            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: [author],
              });
              core.info(`Assigned #${pr.number} to @${author}`);
            } catch (err) {
              core.warning(`Could not assign @${author}: ${err.message}`);
            }
            
